export const coupons = [
    { "id": 1, "title": "ЗАВТРАК В ПОСТЕЛЬ", "subtitle": "медленно\nбез спешки", "used": false },
    { "id": 2, "title": "МАССАЖ СТОП", "subtitle": "пока не захочется\nостановиться", "used": false },
    { "id": 3, "title": "МАССАЖ СПИНЫ", "subtitle": "медленно\nи внимательно", "used": false },
    { "id": 4, "title": "МАССАЖ ГОЛОВЫ", "subtitle": "чтобы мысли\nотпустили", "used": false },
    { "id": 5, "title": "ВАННА ВМЕСТЕ", "subtitle": "с бомбочкой\nи тишиной", "used": false },
    { "id": 6, "title": "ВАННА ВМЕСТЕ", "subtitle": "с пеной\nи временем", "used": false },
    { "id": 7, "title": "ВАННА ВМЕСТЕ", "subtitle": "с солью\nи теплом", "used": false },
    { "id": 8, "title": "РОМАНТИЧЕСКИЙ УЖИН", "subtitle": "без повода\nи сценария", "used": false },
    { "id": 9, "title": "ТИШИНА", "subtitle": "48 часов\nбез сообщений", "used": false },
    { "id": 10, "title": "СЫРНЫЙ ВЕЧЕР", "subtitle": "медленно\nи с вином", "used": false },
    { "id": 11, "title": "ПИВНОЙ ВЕЧЕР", "subtitle": "без ограничений\nи планов", "used": false },
    { "id": 12, "title": "РИСУНОК С НАТУРЫ", "subtitle": "ты смотришь\nя рисую", "used": false },
    { "id": 13, "title": "ЖИВОПИСЬ НЮ", "subtitle": "медленно\nи честно", "used": false },
    { "id": 14, "title": "ПОХОД", "subtitle": "туда где\nменьше людей", "used": false },
    { "id": 15, "title": "ПРОГУЛКА ПО КАНАЛУ", "subtitle": "когда холодно\nи красиво", "used": false },
    { "id": 16, "title": "ОТМЕНА ОБИДЫ", "subtitle": "без объяснений\nи последствий", "used": false },
    { "id": 17, "title": "ЛЮБОЙ ФИЛЬМ", "subtitle": "ты выбираешь\nя рядом", "used": false },
    { "id": 18, "title": "ЛЮБОЕ ВИДЕО", "subtitle": "без комментариев\nи пауз", "used": false },
    { "id": 19, "title": "СЮРПРИЗ", "subtitle": "ты не знаешь\nя знаю", "used": false },
    { "id": 20, "title": "ПИКНИК", "subtitle": "без повода\nи расписания", "used": false },
    { "id": 21, "title": "ТЕАТР", "subtitle": "вечером\nи красиво", "used": false },
    { "id": 22, "title": "КЕРАМИКА", "subtitle": "пачкать руки\nвместе", "used": false },
    { "id": 23, "title": "ДЕНЬ КАПУСТЫ", "subtitle": "как ни странно\nно вкусно", "used": false },
    { "id": 24, "title": "ДЕНЬ ПИРОЖКОВ", "subtitle": "с яйцом\nи детством", "used": false },
    { "id": 25, "title": "ДЕНЬ БЕЗ СПОРОВ", "subtitle": "даже если\nхочется", "used": false },
    { "id": 26, "title": "100 ПОЦЕЛУЕВ", "subtitle": "не подряд\nа как захочется", "used": false },
    { "id": 27, "title": "МУЗЫКА ВМЕСТЕ", "subtitle": "играть\nили слушать", "used": false },
    { "id": 28, "title": "СВИДАНИЕ", "subtitle": "как будто\nвпервые", "used": false },
    { "id": 29, "title": "ЛЕКЦИЯ", "subtitle": "умно\nи интересно", "used": false },
    { "id": 30, "title": "ТВОЁ ЖЕЛАНИЕ", "subtitle": "я не спрашиваю\nты не объясняешь", "used": false },
    { "id": 31, "title": "НЕЖНОСТЬ", "subtitle": "без повода\nи причин", "used": false },
    { "id": 32, "title": "НЕДЕЛЯ БЕЗ УКУСОВ", "subtitle": "честно\nстараюсь", "used": false },
    { "id": 33, "title": "КВЕСТ", "subtitle": "ты не знаешь\nчто дальше", "used": false },
    { "id": 34, "title": "ЯЗЫКИ", "subtitle": "учиться\nи смеяться", "used": false },
    { "id": 35, "title": "СПОРТИВНОЕ СВИДАНИЕ", "subtitle": "двигаться\nи дышать", "used": false },
    { "id": 36, "title": "МАССАЖ", "subtitle": "медленно\nи внимательно", "used": false },
    { "id": 37, "title": "ЗА ГРИБАМИ", "subtitle": "рано утром\nи вместе", "used": false },
    { "id": 38, "title": "НИЧЕГОНЕДЕЛАНИЕ", "subtitle": "официально\nразрешено", "used": false },
    { "id": 39, "title": "ЧТЕНИЕ ВСЛУХ", "subtitle": "вечером\nи тихо", "used": false },
    { "id": 40, "title": "ПРОБЕЖКА", "subtitle": "рядом\nв одном ритме", "used": false },
    { "id": 41, "title": "ЛЮБОВЬ", "subtitle": "без срока\nи условий", "used": false }

  ];